version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
      - CONTAINER_PORT=${CONTAINER_PORT}
    ports:
      - "${APP_PORT}:${CONTAINER_PORT}"
    command: fastapi dev --host 0.0.0.0 --port 8000 app.py